events:
  display-user: display.user
  perform-login: perform.login
  cancel-login: cancel.login

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
    database: 0

web:
  app:
    origin: http://localhost:19006
