web:
  app:
    image-store: /home/glaze
    events:
      display-user: display.user
      perform-login: perform.login
      cancel-login: cancel.login
    origins:
      - http://localhost:19006
      - http://192.169.100.4:19006
      - http://127.0.0.1:19006

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
