web:
  app:
    image-store: /images
    events:
      display-user: display.user
      perform-login: perform.login
      cancel-login: cancel.login
    origins:
      - http://localhost:3000
      - https://glazzes.github.io

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  data:
    redis:
      host: redis
      port: 6379
      database: 0
