version: "3.7"
services:

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    image: glazee/qr-backend:local
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - redis

  web:
    image: glazee/qr-web
    container_name: web
    depends_on:
      - backend
    ports:
      - "3000:80"
